### ISSUE TITLE
Modular Service Module Lander Tank not getting SM-I, SM-II etc

### ISSUE THREAD

**Issue by lpgagnon** [KSP-RO/ROTanks#69]
[As discussed on discord](https://discord.com/channels/319857228905447436/663102368887472156/880628692328529960)

Patch ordering issue, the [ServiceModule->SM-I/II... substitution](https://github.com/KSP-RO/ROTanks/blob/07ba7ed37fa6cb48c8168bf2699e70f5b5ab28a0/GameData/ROTanks/Compatibility/RealismOverhaul.cfg#L1-L12) runs before [the lander tank gets defined](https://github.com/KSP-RO/ROTanks/blob/07ba7ed37fa6cb48c8168bf2699e70f5b5ab28a0/GameData/ROTanks/Parts/Tanks/ROT-NewTanks.cfg#L303-L311)

Easiest is to just replace the type=ServiceModule by a copy-paste of the full set directly in newtanks.cfg (they're both NEEDS:RO, so there's no scenario where the ServiceModule type "should" be left alone), but yuck

**Comment by pap1723** [comment]
Fixed with https://github.com/KSP-RO/ROTanks/commit/69e76e35a1bf67ad2b1f0c123f5d64c0e6c6b339

**Comment by arrowmaster** [comment]
`@PART[ROT-ProbeCore|ROT-*]:AFTER[zzROTanks]:NEEDS[RealismOverhaul]` did not fix the problem and caused Modular Tank (Service Module) to become broken too.

I tested `@PART[ROT-ProbeCore|ROT-*]:FOR[zzzROTanks]:NEEDS[RealismOverhaul]` and both tanks are now working correctly.
